export const products = [
    {
        id: "1",
        name: "Margherita Pizza",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/5/dc74a4b7-8d63-4eb7-91c9-048973c2cc99_1003414.jpg",
        cuisines: ["Italian", "Pizzas"],
        price : 50,
        rating: 1.5,
    },
    {
        id: "2",
        name: "Veggie Burger",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hjao7sorzggaeqito6au",
        cuisines: ["American", "Fast Food"],
        price : 505,
        rating: 1.3,
    },
    {
        id: "3",
        name: "Chicken Biryani",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/gp1ityra6utvzqn6ghnv",
        cuisines: ["Indian", "Biryani"],
        price : 58 ,
        rating: 2.7,
    },
    {
        id: "4",
        name: "Pasta Alfredo",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2274f59cb8efcfab1f446b195bcbda3b",
        cuisines: ["Italian", "Pasta"],
        price : 50,
    },
    {
        id: "5",
        name: "Paneer Butter Masala",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xph0vf5pvbxjf8xchwjk",
        cuisines: ["Indian", "North Indian"],
        price : 57,
        rating: 4.6,
    },
    {
        id: "6",
        name: "Caesar Salad",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/mt2aggiscfl3yviatwng", 
        cuisines: ["Healthy", "Salads"],
        price : 55,
        rating: 4.4,
    },
    {
        id: "7",
        name: "Fried Rice",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/6/21/dbe91f1f-b400-4f4b-a78d-c6b99bdc61c5_912754.JPG", 
        cuisines: ["Chinese", "Asian"],
        price : 50,
    },
    {
        id: "8",
        name: "Tandoori Chicken",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vkhcohhmqfczycw9vsar", // Placeholder for Tandoori Chicken image
        cuisines: ["Indian", "Tandoor"],
        price : 50,
        rating: 4.8,
    },
    {
        id: "9",
        name: "Margherita Pizza",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/5/dc74a4b7-8d63-4eb7-91c9-048973c2cc99_1003414.jpg",
        cuisines: ["Italian", "Pizzas"],
        price : 50,
        rating: 4.5,
    },
    {
        id: "10",
        name: "Veggie Burger",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/hjao7sorzggaeqito6au",
        cuisines: ["American", "Fast Food"],
        price : 50,
        rating: 4.3,
    },
    {
        id: "11",
        name: "Chicken Biryani",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/gp1ityra6utvzqn6ghnv",
        cuisines: ["Indian", "Biryani"],
        price : 50,
        rating: 4.7,
    },
    {
        id: "12",
        name: "Pasta Alfredo",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2274f59cb8efcfab1f446b195bcbda3b",
        cuisines: ["Italian", "Pasta"],
        price : 50,
    },
    {
        id: "13",
        name: "Paneer Butter Masala",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xph0vf5pvbxjf8xchwjk",
        cuisines: ["Indian", "North India "],
        price : 50,
        rating: 4.6,
    },
    {
        id: "14",
        name: "Caesar Salad",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/mt2aggiscfl3yviatwng", 
        cuisines: ["Healthy", "Salads"],
        price : 50,
        rating: 4.4,
    },
    {
        id: "15",
        name: "Fried Rice",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/6/21/dbe91f1f-b400-4f4b-a78d-c6b99bdc61c5_912754.JPG", 
        cuisines: ["Chinese", "Asian"],
        price : 50,
    },
    {
        id: "16",
        name: "Tandoori Chicken",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/vkhcohhmqfczycw9vsar", // Placeholder for Tandoori Chicken image
        cuisines: ["Indian", "Tandoor"],
        price : 50 ,
        rating: 4.8,
    },

]